services:
  mongo:
    image: mongo
    container_name: glycamed-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - glycamed-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: glycamed-backend
    restart: no
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./backend/src:/app/src

    command: ["npm", "run", "dev"]
    networks:
      - glycamed-network

  frontend:
    image: nginx:alpine
    container_name: glycamed-frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - glycamed-network

volumes:
  mongo-data:

networks:
  glycamed-network:
    driver: bridge
